version: "2"
services:
  app:
    build: ./back-end
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
        - ./mysqlSchema:/docker-entrypoint-initdb.d/
        
  web:
    build: ./front-end
    environment:
      - BACK_END_IP=${BACK_END_IP}
    ports:
      - "8080:8080"
    depends_on:
      - app
