version: "2"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


